# Generated by Django 5.2.4 on 2025-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_agent_alter_listing_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='listings.listingimage'),
        ),
    ]
