# Generated by Django 5.2.4 on 2025-07-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='listings.listingimage'),
        ),
    ]
