# Generated by Django 5.2.4 on 2025-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
