# Generated by Django 5.2.4 on 2025-07-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.area'),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.country'),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='Profile Images'),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.region'),
        ),
    ]
