# Generated by Django 5.2.4 on 2025-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_area_account_bio_account_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='area',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
